[package]
name = "git-info"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
ureq = "2.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itertools = "0.13.0"
chrono = "0.4.38"
